[tool.poetry]
name = "sailinganalysis"
version = "0.1.0"
description = ""
authors = ["Felipe Sodr√© M. Barros"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
